### ISSUE TITLE
关于 ImageInterceptor.isIntercept 的一些问题

### ISSUE THREAD

**Issue by libern** [easilycoder/HybridCache#1]
首先，感谢提供如此牛逼的东西！
谢谢年轻的大佬，知道你是刚毕业的！

```
MimeTypeMap.getFileExtensionFromUrl(url)
```
在正常使用中，上述方法貌似不能正确解析。

![image](https://user-images.githubusercontent.com/1830640/42632008-747e5e6c-860e-11e8-905e-b141dc0cf395.png)

如图，导致缓存失败！

**Comment by easilycoder** [comment]
hi，@libern 

初步看了一下MimeTypeMap.getFileExtensionFromUrl(url)这个方法的内部实现，里面有一个正则表达式的匹配规则，按照其规则对于你提及到的图片资源的名称确实无法匹配，所以导致出现了bug。目前想到的解决方案包括（应该也不仅限于）如下：

- 在Android API>=21的时候，请求资源的时候，我们能够拿到请求的头部信息。其中在头部信息中会有一个Accept的key，其中会存储接受的资源类型。比如，如果是图片资源的话，会有一个这样的头部：Accept:image/webp。可以根据这个请求头部确定是否是图片资源，从而拦截图片的请求，进行后续逻辑处理；
- 根据URL的规范，去定义合适的正则表达式的匹配规则，从而正确的获取到资源的类型。

至于最后选择的方案以及具体的实现，后期继续跟进。（问题的出现主要是因为单元测试的工作没有做好。）

**Comment by libern** [comment]
有第三个：
不需要用正则，根据URL规范，直接能提取。
我是用的第三个实现的。

**Comment by easilycoder** [comment]
@libern ，不太理解你说的不使用正则的做法是怎样的。如果不介意的话，方便提供一下的解决方案的细节么？

**Comment by libern** [comment]
送给你吧，这个测试过了。如果不介意的话，可以加我微信，不打不相识，微信名是就是我这个名字。
```
public static String getFileExtensionFromUrl(String url) {
        URL extUrl = null;
        try {
            URI uri = new URI(url);
            extUrl = uri.toURL();
        } catch (URISyntaxException e) {
//            e.printStackTrace();
        } catch (MalformedURLException e) {
//            e.printStackTrace();
        }

        if (extUrl == null) {
            return "";
        }

        String extension = "";
        String path = extUrl.getPath();

        String[] pathContents = path.split("[\\\\/]");
        if (pathContents != null) {
            int pathContentsLength = pathContents.length;
            //lastPart: s659629384_752969_4472.jpg
            String lastPart = pathContents[pathContentsLength - 1];
            String[] lastPartContents = lastPart.split("\\.");
            if (lastPartContents != null && lastPartContents.length > 1) {
                int lastPartContentLength = lastPartContents.length;
                extension = lastPartContents[lastPartContentLength - 1];
            }
        }
        return extension;
    }
```

**Comment by easilycoder** [comment]
#5 bugfix in this pull request.

修改方案：

1. 根据URL获取文件拓展名，检查是否命中对应的文件类型；

2. 对于部分不带拓展名的URL，通过检查请求头部的**Accept**字段，判断请求的是否是image类型的内容。（仅在api21以上有效，并且目前这个校验没有根据mimetype获取具体的图片文件类型，而对于所有的图片类型格式都进行缓存拦截）
