### ISSUE TITLE
最后一个问题

### ISSUE THREAD

**Issue by libern** [easilycoder/HybridCache#4]
哎😔，本来以为你们网易大厂出来的东西不错的。这个需求也正好我需要。但是在我用了之后，发现了特别多的问题。看得出来，这个项目仅仅满足了你们对“图片缓存”的需要，而且并没有其他致命性的问题。但是，当你把这个缓存，拓展到js，css，一大堆问题就来了。。。。虽然已经提了3个issue，但是也没人鸟。

还是你们网易大厂的高冷！

666.

鉴于此，我还是不用你这个问题重重的库了。。。。

**Comment by easilycoder** [comment]
hi, @libern 

很高兴你注意到了这个项目并且尝试去使用了这个项目。

很遗憾因为我的一些私人原因，没法及时的看到并且回复你之前所提的关于这个项目在使用上的遇到的问题。

同时，我很遗憾在这个项目的issue里看到了一条与项目本身技术无关，而有点倾向于情绪的宣泄的issue；我也很遗憾，你把我个人在这个项目的技术实现以及问题处理上的不足归咎到了我的团队（公司），这样的以偏概全，让我为我们的团队（公司）感到不平。

我会在工作之余，尽我最大的时间和能力去思考和解决你先前所提及的问题。

再次感谢你的关注和使用，也感谢你提的意见。同时我也欢迎你，一同去探讨和解决你所遇到的问题。

**Comment by libern** [comment]
总之，还是谢谢！
